In [ ]:
import numpy as np
from numpy import random as nr

nr.seed(11)
r = nr.randint(1, 10, size=(4, 5))
r


In [ ]:
np.sum(r)

In [ ]:
np.average(r)

In [ ]:
np.var(r)

In [ ]:
np.mean(r)

In [ ]:
d = np.arange(1, 6)
d

In [ ]:
np.average(d)

In [ ]:
np.mean(d)

In [ ]:
np.var(d)

In [ ]:
np.std(d)

In [ ]:
r

In [52]:
a = np.array([[3, 2, 4], [8, 7, 1], [9, 6, 5]])
a

array([[3, 2, 4],
       [8, 7, 1],
       [9, 6, 5]])

In [53]:
data = np.sort(a, axis=0)
data

array([[3, 2, 1],
       [8, 6, 4],
       [9, 7, 5]])

In [ ]:
np.sort(a, axis=0)

In [54]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [58]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [59]:
np.linspace(0, 9, 10).reshape(2, 5)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [66]:
np.linspace(0, 9, 6).reshape(2, 3)

array([[0. , 1.8, 3.6],
       [5.4, 7.2, 9. ]])

In [67]:
np.logspace(0, 9, 6, base=np.e).reshape(2, 3)

array([[1.00000000e+00, 6.04964746e+00, 3.65982344e+01],
       [2.21406416e+02, 1.33943076e+03, 8.10308393e+03]])

In [70]:
np.logspace(0, 3, 5)

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])