In [4]:
Nemo = [11, 33.3, 150, "boy", "soccer"]
Jonathan = [13, 50.0, 160, "boy", "fencing"]
print(Nemo)
Jonathan

[11, 33.3, 150, 'boy', 'soccer']


[13, 50.0, 160, 'boy', 'fencing']

In [7]:
import numpy as np
data = np.arange(12).reshape(3, 4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
import numpy as np
data1 = np.array([1, 2, 3]) # 创建一个一维数组
data1

array([1, 2, 3])

In [5]:
data2 = np.array([[1, 2, 3], [4, 5, 6]]) # 创建一个二维数组
data2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
data3 = np.zeros((3, 4))
data3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
data4 = np.ones((2, 3))
data4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
data = np.arange(10, 20)
print(data)
print(data[2:8])

[10 11 12 13 14 15 16 17 18 19]
[12 13 14 15 16 17]


In [3]:
data.ndim

2

In [9]:
import numpy as np
a = np.arange(0, 4)  # 0 1 2 3
b = np.arange(1, 5)  # 1 2 3 4
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))
print(np.power(a, b))

[1 3 5 7]
[-1 -1 -1 -1]
[ 0  2  6 12]
[0.         0.5        0.66666667 0.75      ]
[ 0  1  8 81]


In [20]:
import numpy as np
from numpy import random as nr
np.set_printoptions(precision=2) #显示小数点后两位数
r1 = nr.rand(4, 3)
r1

array([[0.16, 0.23, 0.21],
       [0.04, 0.79, 0.66],
       [0.25, 0.56, 0.65],
       [0.39, 0.8 , 0.02]])

In [35]:
import numpy as np
np.random.seed(22)
a = np.random.randint(0, 10,size=(4, 5))
a

array([[5, 4, 0, 4, 6],
       [6, 4, 8, 4, 2],
       [8, 7, 2, 9, 8],
       [8, 5, 4, 2, 2]])

In [36]:
np.sum(a)

98

In [37]:
np.average(a)

4.9

In [38]:
np.var(a)

6.1899999999999995

In [39]:
np.mean(a)

4.9

In [5]:
import numpy as np

a = np.array([[3, 2, 4], [8, 7, 1], [9, 6, 5]])
a

array([[3, 2, 4],
       [8, 7, 1],
       [9, 6, 5]])

In [10]:
data = np.sort(a, axis=-1)
data

array([[2, 3, 4],
       [1, 7, 8],
       [5, 6, 9]])

In [11]:
np.sort(a, axis=0)

array([[3, 2, 1],
       [8, 6, 4],
       [9, 7, 5]])